### ISSUE TITLE
Possibly allow for an arbitrary target dir

### ISSUE THREAD

**Issue by oalders** [houseabsolute/ubi#10]
On macOS, I don't already have a `$HOME/bin`, but I do have `$HOME/local/bin`, so it's easier for me to install there than to have to add one more dir to my path.

I got it installed by setting `HOME=~/local` before I ran the installer, but it would be nice if the script checked to see if `$TARGET` had already been set before trying to find the right dir.

I can send a PR if you like.

**Comment by autarch** [comment]
You can run `ubi --in $HOME/local/bin ...`. Am I missing something here?

**Comment by oalders** [comment]
Sorry, I meant in the bootstrap script: https://github.com/houseabsolute/ubi/blob/master/bootstrap/bootstrap-ubi.sh#L30-L33

**Comment by autarch** [comment]
Ah, got it! Yes, a PR to make this more flexible this would be great!
