### ISSUE TITLE
ubi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ubi)

### ISSUE THREAD

**Issue by oalders** [houseabsolute/ubi#16]
`ubi` just started triggering an error in my dotfile installer on Ubuntu 18.04. https://github.com/oalders/dot-files/pull/210/checks

```bash
ubi --project houseabsolute/omegasort --in /home/runner/local/bin
ubi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ubi)
Error: Process completed with exit code 1.
```

**Comment by autarch** [comment]
I assume this is with the latest release? I'm guessing that the GH Actions container is now using a newer libc than it did before. I will experiment with ways to fix this.

**Comment by oalders** [comment]
> I assume this is with the latest release?

Yes. This is the first time I've seen this error. The last time the build ran (4 days ago) it was fine.

**Comment by autarch** [comment]
Can you try this one - https://github.com/houseabsolute/ubi/suites/6251160211/artifacts/222461162

That was built on Ubuntu 18.04. It requires glibc 2.27.

Also, what platform are seeing this error on?

**Comment by oalders** [comment]
There's some GitHub magic getting in the way of `curl`:

```
curl -I --location https://github.com/houseabsolute/ubi/suites/6251160211/artifacts/222461162
HTTP/2 404
server: GitHub.com
date: Mon, 25 Apr 2022 18:01:13 GMT
content-type: text/plain; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With
permissions-policy: interest-cohort=()
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
set-cookie: _gh_sess=WqwK6XWbjBH1yZ6dS7bVGIuig8hcJoDUs5o0r7hJcHe9T4culShh1tj%2FRsfdftcvM8qhLuIvd32%2BXOa%2B%2FGjY6BAMoq4yecROA6cHAADuXo1CglU%2B3wNh3CP%2FxD%2FplFiHzDcb9iUhB4MYY2Q2PWuu%2BnnsEuxBNqeUHevyurgJO21S%2FqlRCx2u5kktG%2FKYtWvHCZL4MEz2Q%2BUxcyiXHz%2BsycpUyI%2BmpLzjVFvkr6Q5zfO5Ex4xI747o7UwIiIzhAwsxd%2BYXPkklAkEZ7ddoW4ePg%3D%3D--DwOqrlR5zinoxago--yKKo4qkNXgyfy9x8joZJxQ%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
set-cookie: _octo=GH1.1.180600702.1650909673; Path=/; Domain=github.com; Expires=Tue, 25 Apr 2023 18:01:13 GMT; Secure; SameSite=Lax
set-cookie: logged_in=no; Path=/; Domain=github.com; Expires=Tue, 25 Apr 2023 18:01:13 GMT; HttpOnly; Secure; SameSite=Lax
content-length: 9
x-github-request-id: D02C:7A30:46F6C8:12445D3:6266E1E9
```
> Also, what platform are seeing this error on?

I'm literally just seeing in the GitHub builds for Ubuntu 18.04. It's not getting in the way of my personal workflow yet, but I thought I'd bring it up as someone else might run into it.

**Comment by autarch** [comment]
Ah, if it's Ubuntu 18.04 then I'm sure this will fix it, since that's where the new binary was built.

**Comment by autarch** [comment]
Alright, the v0.0.8 binaries are up and I believe the problem is fixed. Thanks for the report!
