### ISSUE TITLE
Stopped installing omegasort on Ubuntu 20.04

### ISSUE THREAD

**Issue by oalders** [houseabsolute/ubi#26]
I install `omegasort` via GitHub CI as part of testing my `dot-files` repo. This stopped working recently (today?). Here's an example:

https://github.com/oalders/dot-files/actions/runs/3872667868/jobs/6608294844

Here is the installer script in question: https://github.com/oalders/dot-files/blob/main/installer/omegasort.sh

**Comment by autarch** [comment]
Well, that's weird AF. I just tried this on my laptop and it works fine, both with and without a `GITHUB_TOKEN) env var set. My first thought is that something broke in GitHub Actions. Could the GitHub API key available via the `GITHUB_TOKEN` somehow be invalid? But when I test with a bad token it returns a 401, not a 403.

I would suggest rerunning the action again in a day or two to see if this is transient.

**Comment by oalders** [comment]
Yeah, it looks like it's passing on `push` builds and failing on `pull_request`, so I guess it's a GitHub thing.

**Comment by autarch** [comment]
I'm guessing that the `GITHUB_TOKEN` is not available in PR builds for security reasons. It's a little dumb that it doesn't make it available for PRs from repo owners/org members though!

But that doesn't explain the 403 error. Maybe the `GITHUB_TOKEN` has some bogus value? You could try explicitly unsetting it before running `ubi` and see if that fixes it.

**Comment by oalders** [comment]
Interesting. The PR is from dependabot. This what's being run:

```yaml
      - name: Install ubi
        run: ./installer/ubi.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install omegasort
        run: ./installer/omegasort.sh
```

The `ubi` install works in the PR, with the `GITHUB_TOKEN` being explicitly set. The file that passes has the following contents:

```bash
#!/bin/bash

set -eux

INSTALL_DIR="$HOME/local/bin"

# shellcheck disable=SC1090
source "$HOME/dot-files/bash_functions.sh"

if [ ! "$(command -v ubi)" ]; then
    curl --silent --location \
        https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
        TARGET=$INSTALL_DIR sh
    add_path "$INSTALL_DIR"
fi

ubi --project houseabsolute/ubi --in "$INSTALL_DIR"
ubi --project houseabsolute/precious --in "$INSTALL_DIR"
# ubi --project sharkdp/bat --in "$INSTALL_DIR"
# ubi --project sharkdp/fd --in $INSTALL_DIR
# ubi --project Wilfred/difftastic --exe difft --in "$INSTALL_DIR"

exit
```

Maybe I should just set the token on the `omegasort` installer as well?

**Comment by oalders** [comment]
I think we can close this now. Thanks for your help!
