### ISSUE TITLE
Incorrectly extracts directory instead of binary

### ISSUE THREAD

**Issue by rafi** [houseabsolute/ubi#36]
Running `ubi -p aristocratos/btop` extracts the directory `btop`, instead of `btop/bin/btop` binary,.

**Comment by autarch** [comment]
Thanks for this bug report. The logic for finding the binary isn't very smart right now. It just looks for anything in the zip/tarball matching the expected binary name. The fix is to make it look for a _file_ matching that name.

**Comment by autarch** [comment]
Looks like this is fairly easy for tarballs and AFAICT directories aren't stored separately in zip files. They're just implicit as part of the file names.

**Comment by autarch** [comment]
This is fixed in v0.0.25.
