### ISSUE TITLE
Bootstrap not working, maybe allow forcing arch

### ISSUE THREAD

**Issue by oanylund** [houseabsolute/ubi#38]
Hi,

Thanks for ubi!

When bootstrapping ubi on two different distributions of Linux I get:
`boostrap-ubi.sh: Cannot determine what binary to download for your CPU architecture`

`uname -m` returns `armv7l` on one and `aarch64` on the other.
For reference this is on Raspberry Pi OS and Ubuntu Server (also running on a rpi)

Could it be good to have to allow forcing aarch when bootstrapping?

**Comment by autarch** [comment]
Adding support for more platforms shouldn't be too hard. I just need to get the `uname -m` and `uname -s` output from them. But I'd also be up for a PR that adds support for just using `KERNEL` and `ARCH` variables if they're set.

**Comment by autarch** [comment]
Actually, it occurs to me that maybe it'd better to just allow _one_ env var that is the file name to download. That's probably simpler to use and document.

**Comment by oanylund** [comment]
I think that is a good option which will work nicely as a last resort and requires no maintenance from a developer pov. 👍

**Comment by autarch** [comment]
I updated the bootstrap script to try to handle more platforms and CPU architectures. It now also checks for a `FILENAME` argument which can be used to bypass platform detection entirely.
