### ISSUE TITLE
Fails to match using --matching

### ISSUE THREAD

**Issue by oanylund** [houseabsolute/ubi#40]
Hi,

I had two releases with the following pattern

- arm64_musl.tar.gz
- arm71_gnu.tar.gz

When running ubi with `--debug` it found `cpu` architecture of type `arm`
It then said it had two matches and could not determine which to choose.
 
Adding a `--matches arm64` or `--matches arm71` to the command returns the error `could not find any assets containing our --matching string`.

Just browsing at the code, could it be that the [vector](https://github.com/houseabsolute/ubi/blob/master/src/ubi.rs#L415-L448) at L415 is empty because it did not match 64 bit at L416 and it is trying to match against an empty vector at L439. 
Should the matches string not be matched against all remaining assets if all else fails?

**Comment by autarch** [comment]
Thanks for the bug report! This is definitely a bug. I have a fix in progress.

**Comment by autarch** [comment]
This should be fixed in v0.0.26.

**Comment by oanylund** [comment]
Awesome 👌
