### ISSUE TITLE
Gitea or Gitlab support?

### ISSUE THREAD

**Issue by SangeloDev** [houseabsolute/ubi#51]
Hi there,
I just found this project, and read into it. I see that `ubi` is designed to work with GitHub repositories, but I find no mention of Gitlab or Gitea. This leads me to believe that there is no support for other git forges.

I wanted to quickly ask if this is the case, or if something is planned, or if there's already support for that.

Thanks, have a nice day!

**Comment by autarch** [comment]
There's no support for other forges right now. I'd be open to a PR to add such support.

**Comment by yodatak** [comment]
I would love to use it for using in mise for gitlab-cli tools

**Comment by yodatak** [comment]
I do some search to find somethink similar 
https://github.com/search?q=https%3A%2F%2Fgitlab.com%2Fapi%2Fv4%2Fprojects%2F+lang%3Arust&type=code
https://github.com/agateau/clyde/blob/b0e837616ddce9c3168b286e944da6069bf1f2f2/src/bin/clydetools/gitlab_fetcher.rs#L82
https://github.com/Roblox/foreman/blob/8728d5954d8ba2b865961531759d42fc22668b49/src/tool_provider/gitlab.rs#L33
https://github.com/orbiter-rs/orbiter/blob/ba87b84ba9a0daf3cb1de7cef9e835102d5f7800/src/providers/github.rs#L4

**Comment by autarch** [comment]
Yeah, it's definitely doable. I think the biggest challenge isn't working with the GitLab API. It's going to be more challenging to refactor the `ubi` internals so that it supports multiple release artifact sources.

**Comment by reteps** [comment]
+1 on GitLab support. For example, I need to install graphviz. https://gitlab.com/graphviz/graphviz/-/releases/12.2.1

**Comment by autarch** [comment]
I will have GitLab support in the next release (0.3.0). But I'd note that graphviz isn't a good use case for `ubi`, for several reasons. First, graphviz isn't really a single-file binary. It's a collection of binaries. See #68 for some discussion around supporting this.

But even then, on Linux, they only release compiled artifacts as debs and rpms. So `ubi` would be able to install this on Linux because of that.

**Comment by autarch** [comment]
This is done in the v0.3.0 release.
