### ISSUE TITLE
failed to select a version for the requirement `zip = "^1.2.2"`

### ISSUE THREAD

**Issue by risu729** [houseabsolute/ubi#58]
I cannot install ubi with cargo due to the yanked zip version.
Since it is already resolved in the master branch, could you cut a new release?

Thanks so much for this awesome tool.

```
error: failed to compile `ubi v0.0.30`, intermediate artifacts can be found at `/tmp/cargo-installjPVRUA`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to select a version for the requirement `zip = "^1.2.2"`
  candidate versions found which didn't match: 2.1.1, 2.1.0, 2.0.0, ...
  location searched: crates.io index
  required by package `ubi v0.0.30`
  if you are looking for the prerelease package it needs to be specified explicitly
      zip = { version = "0.10.0-alpha.1" }
  perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by autarch** [comment]
Done.

But I'd note the main reason I wrote `ubi` was to avoid having to install things by compiling them. There are bootstrap shell scripts you can use to install `ubi` without running `cargo`. See https://github.com/houseabsolute/ubi/tree/v0.0.31?tab=readme-ov-file#installing-it for details.

**Comment by risu729** [comment]
Thanks for the new release!

I understand and agree with the philosophy. However, I'm using `ubi` as a `mise` (tool version manager) backend, and `mise` does not support installing `ubi` without `cargo`.
I will be able to install pre-compiled `ubi` with `mise` by making its [plugin](https://mise.jdx.dev/dev-tools/backends/asdf.html#writing-asdf-plugins-for-mise), so I will work on it soon.
docs: https://mise.jdx.dev/dev-tools/backends/ubi.html
