### ISSUE TITLE
renovate

### ISSUE THREAD

**Issue by jdx** [houseabsolute/ubi#61]
would you consider adding renovate or dependabot? I recommend renovate, here's the config I use in my rust projects if you want a reference:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "automerge": true,
  "dependencyDashboard": false,
  "extends": [
    "config:recommended",
    "schedule:earlyMondays"
  ],
  "lockFileMaintenance": {
    "enabled": false
  },
  "timezone": "America/Chicago"
}
```

Adding this would keep the dependencies up to date and reduce duplication within mise.

**Comment by autarch** [comment]
I set up dependabot since GitHub makes it easy to do so. I'll see how I like it.
