### ISSUE TITLE
Documentation for GitHub Enterprise

### ISSUE THREAD

**Issue by oalders** [houseabsolute/ubi#69]
I don't see any docs on how to use `ubi` with GitHub enterprise. Not sure if I'm missing something obvious.

**Comment by autarch** [comment]
There's no way to use it with GH Enterprise right now. There'd need to be a way to set the domain name that replaces the GitHub domains currently hard-coded. PRs welcome!

**Comment by autarch** [comment]
The v0.3.0 release now includes an `--api-base-url` CLI argument. You should be able to set this to something like `https://github.my-corp.example.com/api/v4` to use an Enterprise installation.
